// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDocNC8zguMvpm_qYWWuXWCWY6Z41hp-eQ',
    appId: '1:640696484068:web:dafcb0c8fde6c5efc9acf1',
    messagingSenderId: '640696484068',
    projectId: 'jobology-8cf83',
    authDomain: 'jobology-8cf83.firebaseapp.com',
    storageBucket: 'jobology-8cf83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADGyRVfzL0LqcAGLE1mBCglUSJLTpRnGc',
    appId: '1:640696484068:android:a8635454faf13d3bc9acf1',
    messagingSenderId: '640696484068',
    projectId: 'jobology-8cf83',
    storageBucket: 'jobology-8cf83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Kgsg9DNgfQY2XSO8vFbDmLi-EKm1QwQ',
    appId: '1:640696484068:ios:7167c54190de5d72c9acf1',
    messagingSenderId: '640696484068',
    projectId: 'jobology-8cf83',
    storageBucket: 'jobology-8cf83.appspot.com',
    iosClientId: '640696484068-c05dlo4t6tpqrbllehvduh4mp55lum47.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobology',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Kgsg9DNgfQY2XSO8vFbDmLi-EKm1QwQ',
    appId: '1:640696484068:ios:7167c54190de5d72c9acf1',
    messagingSenderId: '640696484068',
    projectId: 'jobology-8cf83',
    storageBucket: 'jobology-8cf83.appspot.com',
    iosClientId: '640696484068-c05dlo4t6tpqrbllehvduh4mp55lum47.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobology',
  );
}
